version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*_gen.go"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - gocritic
    - gosimple
    - unparam
    - unused
    - revive
  disable:
    - maligned
    - lll

linters-settings:
  revive:
    severity: warning
    ignoreGeneratedHeader: true
  gocritic:
    disabled-checks:
      - commentFormatting
      - hugeParam

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "Error return value is not checked.*(Close|Write|Flush).*"
    - "should have comment or be unexported"

formatters:
  enable:
    - govet
    - gofmt
    - goimports
