version: "2.0"

# Liste des linters activés
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - gocritic
    - gosimple
    - unparam
    - unused
    - revive

# Répertoires et fichiers à exclure
exclude-dirs:
  - vendor
exclude-files:
  - ".*_gen.go"

# Exclure certaines règles
exclude-rules:
  - linters:
      - errcheck
    text: "Error return value is not checked.*(Close|Write|Flush).*"
  - linters:
      - golint
    text: "should have comment or be unexported"

# Paramètres spécifiques à certains linters
linters-settings:
  revive:
    severity: warning
    ignoreGeneratedHeader: true
  gocritic:
    disabled-checks:
      - commentFormatting
      - hugeParam
