name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.1

      - name: Download dependencies
        run: go mod tidy

      - name: Install golangci-lint (official binary)
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.53.3

      - name: Run golangci-lint
        run: golangci-lint run ./...
