name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.1

      - name: Download dependencies
        run: go mod download

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.3

      - name: Add Go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Run golangci-lint
        run: golangci-lint run ./...
