name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Installation de la bonne version de Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25.1

      # 3️⃣ Nettoyage du cache Go pour éviter les conflits
      - name: Clear Go mod cache
        run: go clean -modcache

      # 4️⃣ Téléchargement des dépendances
      - name: Download dependencies
        run: go mod tidy

      # 5️⃣ Installation de golangci-lint via Go
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

      # 6️⃣ Ajout de golangci-lint au PATH
      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      # 7️⃣ Exécution du linter
      - name: Run golangci-lint
        run: golangci-lint run ./...
